  CREATE TABLE CCT001.CCM_ICM_AGNT 
   (	
   SKILL_TGT_ID NUMBER(10,0) NOT NULL ENABLE, 
	PERSON_ID NUMBER(10,0), 
	AGNT_DESK_SETTINGS_ID NUMBER(10,0), 
	SCHEDULE_ID NUMBER(10,0), 
	PERIPHERAL_ID NUMBER(5,0), 
	ENTERPRISE_NAM VARCHAR2(32 CHAR), 
	PERIPHERAL_NBR VARCHAR2(32 CHAR), 
	CONFIG_PARAM VARCHAR2(255 CHAR), 
	DESCRIPTION VARCHAR2(255 CHAR), 
	DELETED_FLG VARCHAR2(1 CHAR), 
	PERIPHERAL_NAM VARCHAR2(32 CHAR), 
	TEMP_AGNT_FLG VARCHAR2(1 CHAR), 
	AGNT_STATE_TRACE VARCHAR2(1 CHAR), 
	SUPERV_AGNT_FLG VARCHAR2(1 CHAR), 
	CHANGE_STAMP NUMBER(10,0), 
	USER_DELETABLE_FLG VARCHAR2(1 CHAR), 
	DEF_SKILL_GRP NUMBER(10,0)
   );

  CREATE UNIQUE INDEX CCT001.CCM_ICM_AGNT_UIX01 ON CCT001.CCM_ICM_AGNT (SKILL_TGT_ID);
  
  CREATE TABLE CCT001.CONFIGURATION
(
   CODE varchar(100) NOT NULL,
   CATEGORY varchar(100) NOT NULL,
   VALUE varchar(4000),
   DESCRIPTION varchar(200),
   ACTIVE_FLG char(1) NOT NULL,
   MAINT_DTM timestamp DEFAULT CURRENT_TIMESTAMP NULL,
   MAINT_USERID char(8) DEFAULT CURRENT_USER NULL,
   PRIMARY KEY (CODE,CATEGORY)
)
;

CREATE UNIQUE INDEX XPKCONFIG01 ON "CCT001"."CONFIGURATION"
(
  CODE,
  CATEGORY
)
;

ALTER TABLE "CCT001"."CONFIGURATION" ADD CONSTRAINT "CKYN04" CHECK (
ACTIVE_FLG IN ('Y', 'N'));





CREATE TABLE CCT001.JOB_CTRL_TXN
(
   JOB_CTRL_TXN_ID int PRIMARY KEY NOT NULL,
   JOB_CTRL_ID int NOT NULL,
   STATUS char(1) NOT NULL,
   START_DTM timestamp,
   END_DTM timestamp,
   START_ID bigint,
   END_ID bigint,
   MAINT_APP char(8),
   ACTIVITY_DT DATE NULL
);

CREATE SEQUENCE CCT001.JOB_CTRL_SEQ START WITH 100;
CREATE SEQUENCE CCT001.JOB_CTRL_TXN_SEQ AS INTEGER START WITH 1;
CREATE TABLE CCT001.JOB_CTRL
(
   JOB_CTRL_ID int PRIMARY KEY NOT NULL,
   JOB_NAM varchar(20) NOT NULL,
   DB_CD varchar(4) NOT NULL,
   TBL_NAM varchar(20) NOT NULL,
   FREQ_CD char(1),
   BEHAV_CD char(1),
   ID_COL_NAM varchar(20),
   UPDT_COL_NAM varchar(20),
   CRTD_COL_NAM varchar(20),
   MAINT_APP char(8)
);