-- Batch Job Launch start

CREATE TABLE "CCT001"."BATCH_JOB_LNCH" (
		"BATCH_JOB_LNCH_ID" BIGINT NOT NULL, 
		"JOB_LNCH_NAME" VARCHAR(100) DEFAULT NULL, 
		"JOB_CTX_FILE_LOC" VARCHAR(255) DEFAULT NULL, 
		"JOB_NAME" VARCHAR(100) DEFAULT NULL, 
		"INSERT_DTM" TIMESTAMP DEFAULT NULL, 
		"VERSION" INTEGER DEFAULT NULL, 
		"NEW_INSTANCE_FLG" CHAR(1) DEFAULT NULL, 
		"ACTIVE_FLG" CHAR(1) DEFAULT NULL, 
		"DAILY_FLG" CHAR(1) DEFAULT NULL, 
		"JOB_TYPE" CHAR(3) DEFAULT NULL, 
		"KILL_FLG" CHAR(1) DEFAULT 'N' NOT NULL, 
		"START_DTM" TIMESTAMP DEFAULT NULL, 
		"OUTAGE_FILE_LOC" VARCHAR(200) DEFAULT NULL
	);

CREATE UNIQUE INDEX "CCT001"."XPKBATCH_J_LNCH"
	ON "CCT001"."BATCH_JOB_LNCH"
	("BATCH_JOB_LNCH_ID"		ASC);

ALTER TABLE "CCT001"."BATCH_JOB_LNCH" ADD CONSTRAINT "CKLDYN06" 
CHECK (NEW_INSTANCE_FLG IN ('Y','N'));

ALTER TABLE "CCT001"."BATCH_JOB_LNCH" ADD CONSTRAINT "CKLDYN07" 
CHECK (ACTIVE_FLG IN ('Y','N'));

ALTER TABLE "CCT001"."BATCH_JOB_LNCH" ADD CONSTRAINT "CKLDYN08" 
CHECK (DAILY_FLG   IN ('Y','N'));

ALTER TABLE "CCT001"."BATCH_JOB_LNCH" ADD CONSTRAINT "CKLDYN09" 
CHECK (KILL_FLG  IN ('Y', 'N'));

ALTER TABLE "CCT001"."BATCH_JOB_LNCH" ADD CONSTRAINT 
"XPKBATCH_J_LNCH" PRIMARY KEY
	("BATCH_JOB_LNCH_ID");

-- Batch Job Launch end

	
-- Batch Lnch Params start

CREATE TABLE "CCT001"."BATCH_LNCH_PARAMS" (
		"BATCH_JOB_LNCH_ID" BIGINT NOT NULL, 
		"JOB_PARAM_ID" BIGINT NOT NULL, 
		"JOB_PARAM_NAME" VARCHAR(100) DEFAULT NULL, 
		"JOB_PARAM_VALUE" VARCHAR(255) DEFAULT NULL, 
		"INSERT_DTM" TIMESTAMP DEFAULT NULL
	);

CREATE UNIQUE INDEX "CCT001"."XPKBATCH_L_PAR"
	ON "CCT001"."BATCH_LNCH_PARAMS"
	("BATCH_JOB_LNCH_ID"		ASC, 
	  "JOB_PARAM_ID"		ASC);

ALTER TABLE "CCT001"."BATCH_LNCH_PARAMS" ADD CONSTRAINT 
"XPKBATCH_L_PAR" PRIMARY KEY
	("BATCH_JOB_LNCH_ID", 
	 "JOB_PARAM_ID");

ALTER TABLE "CCT001"."BATCH_LNCH_PARAMS" ADD CONSTRAINT 
"RELATIONSHIP143" FOREIGN KEY
	("BATCH_JOB_LNCH_ID")
	REFERENCES "CCT001"."BATCH_JOB_LNCH"
	("BATCH_JOB_LNCH_ID")
	ON DELETE RESTRICT;
