-- Batch Job Launch start

CREATE TABLE CCT001.BATCH_JOB_LAUNCH (
		BATCH_JOB_LAUNCH_ID NUMBER(14,0) NOT NULL, 
		JOB_LAUNCH_NAME VARCHAR2(100 CHAR) DEFAULT NULL, 
		JOB_CTX_FILE_LOC VARCHAR2(255 CHAR) DEFAULT NULL, 
		JOB_NAME VARCHAR2(100 CHAR) DEFAULT NULL, 
		INSERT_DTM TIMESTAMP DEFAULT NULL, 
		VERSION NUMBER(8,0) DEFAULT NULL, 
		NEW_INSTANCE_FLG CHAR(1) DEFAULT NULL, 
		ACTIVE_FLG VARCHAR2(1 CHAR) DEFAULT NULL, 
		DAILY_FLG VARCHAR2(1 CHAR) DEFAULT NULL, 
		JOB_TYPE VARCHAR2(3 CHAR) DEFAULT NULL, 
		KILL_FLG VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL, 
		START_DTM TIMESTAMP DEFAULT NULL, 
		OUTAGE_FILE_LOC VARCHAR2(200 CHAR) DEFAULT NULL
	);

CREATE UNIQUE INDEX CCT001.XPKBATCH_J_LAUNCH
	ON CCT001.BATCH_JOB_LAUNCH
	(BATCH_JOB_LAUNCH_ID		ASC);

ALTER TABLE CCT001.BATCH_JOB_LAUNCH ADD CONSTRAINT CKLDYN06 
CHECK (NEW_INSTANCE_FLG IN ('Y','N'));

ALTER TABLE CCT001.BATCH_JOB_LAUNCH ADD CONSTRAINT CKLDYN07 
CHECK (ACTIVE_FLG IN ('Y','N'));

ALTER TABLE CCT001.BATCH_JOB_LAUNCH ADD CONSTRAINT CKLDYN08 
CHECK (DAILY_FLG   IN ('Y','N'));

ALTER TABLE CCT001.BATCH_JOB_LAUNCH ADD CONSTRAINT CKLDYN09 
CHECK (KILL_FLG  IN ('Y', 'N'));

ALTER TABLE CCT001.BATCH_JOB_LAUNCH ADD CONSTRAINT 
XPKBATCH_J_LAUNCH PRIMARY KEY
	(BATCH_JOB_LAUNCH_ID);

-- Batch Job Launch end

	
-- Batch LAUNCH Params start

CREATE TABLE CCT001.BATCH_LAUNCH_PARAMS (
		BATCH_JOB_LAUNCH_ID NUMBER(14,0) NOT NULL, 
		JOB_PARAM_ID NUMBER(14,0) NOT NULL, 
		JOB_PARAM_NAME VARCHAR2(100 CHAR) DEFAULT NULL, 
		JOB_PARAM_VALUE VARCHAR2(255 CHAR) DEFAULT NULL, 
		INSERT_DTM TIMESTAMP DEFAULT NULL
	);

CREATE UNIQUE INDEX CCT001.XPKBATCH_L_PAR
	ON CCT001.BATCH_LAUNCH_PARAMS
	(BATCH_JOB_LAUNCH_ID		ASC, 
	  JOB_PARAM_ID		ASC);

ALTER TABLE CCT001.BATCH_LAUNCH_PARAMS ADD CONSTRAINT 
XPKBATCH_L_PAR PRIMARY KEY
	(BATCH_JOB_LAUNCH_ID, 
	 JOB_PARAM_ID);

ALTER TABLE CCT001.BATCH_LAUNCH_PARAMS ADD CONSTRAINT 
RELATIONSHIP143 FOREIGN KEY
	(BATCH_JOB_LAUNCH_ID)
	REFERENCES CCT001.BATCH_JOB_LAUNCH
	(BATCH_JOB_LAUNCH_ID)
	ON DELETE RESTRICT;
