--NEW BATCH TABLES FOR SPRING BATCH 3
CREATE TABLE CCT001.BATCH_JOB_INSTANCE  (
    JOB_INSTANCE_ID NUMBER(14,0)  NOT NULL PRIMARY KEY ,
    VERSION NUMBER(14,0) ,
    JOB_NAME VARCHAR2(100 CHAR) NOT NULL,
    JOB_KEY VARCHAR2(32 CHAR) NOT NULL,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE CCT001.BATCH_JOB_EXECUTION  (
    JOB_EXECUTION_ID NUMBER(14,0)  NOT NULL PRIMARY KEY ,
    VERSION NUMBER(14,0)  ,
    JOB_INSTANCE_ID NUMBER(14,0) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL ,
    END_TIME TIMESTAMP DEFAULT NULL ,
    STATUS VARCHAR2(10 CHAR) ,
    EXIT_CODE VARCHAR2(2500 CHAR) ,
    EXIT_MESSAGE VARCHAR2(2500 CHAR) ,
    LAST_UPDATED TIMESTAMP,
    JOB_CONFIGURATION_LOCATION VARCHAR2(2500) NULL,
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
    references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE CCT001.BATCH_JOB_EXECUTION_PARAMS  (
    JOB_EXECUTION_ID NUMBER(14,0) NOT NULL ,
    TYPE_CD VARCHAR2(6 CHAR) NOT NULL ,
    KEY_NAME VARCHAR2(100 CHAR) NOT NULL ,
    STRING_VAL VARCHAR2(250 CHAR) ,
    DATE_VAL TIMESTAMP DEFAULT NULL ,
    LONG_VAL NUMBER(14,0) ,
    DOUBLE_VAL DOUBLE ,
    IDENTIFYING VARCHAR2(1 CHAR) NOT NULL ,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE CCT001.BATCH_STEP_EXECUTION  (
    STEP_EXECUTION_ID NUMBER(14,0)  NOT NULL PRIMARY KEY ,
    VERSION NUMBER(14,0) NOT NULL,
    STEP_NAME VARCHAR2(100) NOT NULL,
    JOB_EXECUTION_ID NUMBER(14,0) NOT NULL,
    START_TIME TIMESTAMP NOT NULL ,
    END_TIME TIMESTAMP DEFAULT NULL ,
    STATUS VARCHAR2(10) ,
    COMMIT_COUNT NUMBER(14,0) ,
    READ_COUNT NUMBER(14,0) ,
    FILTER_COUNT NUMBER(14,0) ,
    WRITE_COUNT NUMBER(14,0) ,
    READ_SKIP_COUNT NUMBER(14,0) ,
    WRITE_SKIP_COUNT NUMBER(14,0) ,
    PROCESS_SKIP_COUNT NUMBER(14,0) ,
    ROLLBACK_COUNT NUMBER(14,0) ,
    EXIT_CODE VARCHAR2(2500 CHAR) ,
    EXIT_MESSAGE VARCHAR2(2500 CHAR) ,
    LAST_UPDATED TIMESTAMP,
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE CCT001.BATCH_STEP_EXECUTION_CONTEXT  (
    STEP_EXECUTION_ID NUMBER(14,0) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR2(2500 CHAR) NOT NULL,
    SERIALIZED_CONTEXT CLOB ,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
    references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE CCT001.BATCH_JOB_EXECUTION_CONTEXT  (
    JOB_EXECUTION_ID NUMBER(14,0) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR2(2500 CHAR) NOT NULL,
    SERIALIZED_CONTEXT CLOB ,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

--SEQUENCES
CREATE SEQUENCE CCT001.BATCH_STEP_EXECUTION_SEQ START WITH 1;
CREATE SEQUENCE CCT001.BATCH_JOB_EXECUTION_SEQ START WITH 1;
CREATE SEQUENCE CCT001.BATCH_JOB_SEQ START WITH 1;

--TABLE REPRESENTATIONS OF SEQUENCES
CREATE TABLE CCT001.BATCH_STEP_EXECUTION_SEQ (ID BIGINT IDENTITY);
CREATE TABLE CCT001.BATCH_JOB_EXECUTION_SEQ (ID BIGINT IDENTITY);
CREATE TABLE CCT001.BATCH_JOB_SEQ (ID BIGINT IDENTITY);