--NEW BATCH TABLES FOR SPRING BATCH 3
CREATE TABLE CCT001.BATCH_JOB_INSTANCE  (
    JOB_INSTANCE_ID DECIMAL(14,0)  NOT NULL PRIMARY KEY ,
    VERSION DECIMAL(14,0) ,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE CCT001.BATCH_JOB_EXECUTION  (
    JOB_EXECUTION_ID DECIMAL(14,0)  NOT NULL PRIMARY KEY ,
    VERSION DECIMAL(14,0)  ,
    JOB_INSTANCE_ID DECIMAL(14,0) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL ,
    END_TIME TIMESTAMP DEFAULT NULL ,
    STATUS VARCHAR(10) ,
    EXIT_CODE VARCHAR(2500) ,
    EXIT_MESSAGE VARCHAR(2500) ,
    LAST_UPDATED TIMESTAMP,
    JOB_CONFIGURATION_LOCATION VARCHAR(2500) NULL,
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
    references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE CCT001.BATCH_JOB_EXECUTION_PARAMS  (
    JOB_EXECUTION_ID DECIMAL(14,0) NOT NULL ,
    TYPE_CD VARCHAR(6) NOT NULL ,
    KEY_NAME VARCHAR(100) NOT NULL ,
    STRING_VAL VARCHAR(250) ,
    DATE_VAL TIMESTAMP DEFAULT NULL ,
    LONG_VAL DECIMAL(14,0) ,
    DOUBLE_VAL DOUBLE ,
    IDENTIFYING CHAR(1) NOT NULL ,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE CCT001.BATCH_STEP_EXECUTION  (
    STEP_EXECUTION_ID DECIMAL(14,0)  NOT NULL PRIMARY KEY ,
    VERSION DECIMAL(14,0) NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID DECIMAL(14,0) NOT NULL,
    START_TIME TIMESTAMP NOT NULL ,
    END_TIME TIMESTAMP DEFAULT NULL ,
    STATUS VARCHAR(10) ,
    COMMIT_COUNT DECIMAL(14,0) ,
    READ_COUNT DECIMAL(14,0) ,
    FILTER_COUNT DECIMAL(14,0) ,
    WRITE_COUNT DECIMAL(14,0) ,
    READ_SKIP_COUNT DECIMAL(14,0) ,
    WRITE_SKIP_COUNT DECIMAL(14,0) ,
    PROCESS_SKIP_COUNT DECIMAL(14,0) ,
    ROLLBACK_COUNT DECIMAL(14,0) ,
    EXIT_CODE VARCHAR(2500) ,
    EXIT_MESSAGE VARCHAR(2500) ,
    LAST_UPDATED TIMESTAMP,
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE CCT001.BATCH_STEP_EXECUTION_CONTEXT  (
    STEP_EXECUTION_ID DECIMAL(14,0) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB ,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
    references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE CCT001.BATCH_JOB_EXECUTION_CONTEXT  (
    JOB_EXECUTION_ID DECIMAL(14,0) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB ,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

--SEQUENCES
CREATE SEQUENCE CCT001.BATCH_STEP_EXECUTION_SEQ START WITH 1;
CREATE SEQUENCE CCT001.BATCH_JOB_EXECUTION_SEQ START WITH 1;
CREATE SEQUENCE CCT001.BATCH_JOB_SEQ START WITH 1;

--TABLE REPRESENTATIONS OF SEQUENCES
CREATE TABLE CCT001.BATCH_STEP_EXECUTION_SEQ (ID BIGINT IDENTITY);
CREATE TABLE CCT001.BATCH_JOB_EXECUTION_SEQ (ID BIGINT IDENTITY);
CREATE TABLE CCT001.BATCH_JOB_SEQ (ID BIGINT IDENTITY);