delete from CCT001.batch_LAUNCH_params where BATCH_JOB_LAUNCH_ID = 1250;
delete from CCT001.batch_job_LAUNCH where BATCH_JOB_LAUNCH_ID = 1250;

--Delete old TXN records
delete from CCT001.job_ctrl_txn where job_ctrl_id in ( select job_ctrl_id from CCT001.job_ctrl where JOB_NAM = 'SUBEDIFILE_J01');
--Delete old CTRL records
delete from CCT001.job_ctrl where JOB_NAM = 'SUBEDIFILE_J01';

--------------------------------------------------------------------------------
insert into CCT001.batch_job_LAUNCH (
	BATCH_JOB_LAUNCH_ID, JOB_LAUNCH_NAME, JOB_CTX_FILE_LOC, JOB_NAME, 
	VERSION, NEW_INSTANCE_FLG, ACTIVE_FLG, DAILY_FLG, JOB_TYPE
) values (
	1250, 'SUBEDIFILE_J01', 'SUBEDIFILE_J01-context.xml', 'SUBEDIFILE_J01',
	0, 'Y', 'Y', 'N', 'CCM'
);

---------------------------------------------------------------------------------
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 1, 'option.job.launcher', 'yes');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 2, 'job.launcher.sbparam', 'DELIMITER.CHARACTER=|');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 3, 'job.launcher.sbparam', 'COMMIT.INTERVAL=500');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 4, 'job.launcher.sbparam', 'FILE.ENCODING=UTF-8');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 5, 'job.launcher.sbparam', 'JOB.NAME=SUBEDIFILE_J01');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 6, 'job.launcher.sbparam', 'DATABASE.CODE=ICM');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 7, 'job.launcher.sbparam', 'FILE.CATAGORY=SUBEDI_ANALYTICS');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 8, 'job.launcher.sbparam', 'FILE.STATUS=NEW');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 9, 'job.launcher.sbparam', 'FILE.TYPE=ICM');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 10, 'job.launcher.sbparam', 'MAPPING.NAME=CCM_ICM_MAPPING');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 11, 'job.launcher.sbparam', 'PROCESS.FAILED=true');
insert into CCT001.BATCH_LAUNCH_PARAMS (BATCH_JOB_LAUNCH_ID, JOB_PARAM_ID, JOB_PARAM_NAME, JOB_PARAM_VALUE) values (
	1251, 12, 'job.launcher.sbparam', 'MAX.RUN.COUNT=50');
--------------------------------------------------------------------------------

-- insert for job_ctrl_table
INSERT INTO CCT001.JOB_CTRL (JOB_CTRL_ID,JOB_NAME,DB_CD,TBL_NAME,FREQ_CD,BEHAV_CD, MAINT_APP) VALUES((CCT001.JOB_CTRL_SEQ.NEXTVAL),'SUBEDIFILE_J01','ICM','AGNT','D','M',  USER);
	
	
-- INSERT STATEMENTS FOR REFERENCE DATA
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','SkillTargetID','Y','CCM_ICM_AGNT','SKILL_TGT_ID','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','PersonID','N','CCM_ICM_AGNT','PERSON_ID','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','AgentDeskSettingsID','N','CCM_ICM_AGNT','AGNT_DESK_SETTINGS_ID','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','ScheduleID','N','CCM_ICM_AGNT','SCHEDULE_ID','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','PeripheralID','N','CCM_ICM_AGNT','PERIPHERAL_ID','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','EnterpriseName','N','CCM_ICM_AGNT','ENTERPRISE_NAM','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','PeripheralNumber','N','CCM_ICM_AGNT','PERIPHERAL_NBR','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','ConfigParam','N','CCM_ICM_AGNT','CONFIG_PARAM','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','Description','N','CCM_ICM_AGNT','DESCRIPTION','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','Deleted','N','CCM_ICM_AGNT','DELETED_FLG','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','PeripheralName','N','CCM_ICM_AGNT','PERIPHERAL_NAM','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','TemporaryAgent','N','CCM_ICM_AGNT','TEMP_AGNT_FLG','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','AgentStateTrace','N','CCM_ICM_AGNT','AGNT_STATE_TRACE','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','SupervisorAgent','N','CCM_ICM_AGNT','SUPERV_AGNT_FLG','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','ChangeStamp','N','CCM_ICM_AGNT','CHANGE_STAMP','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','UserDeletable','N','CCM_ICM_AGNT','USER_DELETABLE_FLG','Y');
INSERT INTO CCT001.CCM_REF (REF_GROUP_NAME,REF_GROUP_KEY1,REF_GROUP_KEY2,REF_GROUP_KEY3,FIELD_NAME1,FIELD_NAME2,ACTIVE_FLG) VALUES ('CCM_ICM_MAPPING','Agent','DefaultSkillGroup','N','CCM_ICM_AGNT','DEF_SKILL_GRP','Y');











	
	
	